import typing
from typing import ClassVar, overload

class AlreadySent(RuntimeError): ...

class Consumer:
    def __init__(self, stream_name: str, cancel_event: object = ..., polling_interval: typing.SupportsFloat = ..., context: str = ...) -> None: ...
    def receive(self, minimum_ts: typing.SupportsInt = ..., blocking: bool = ...) -> ReadBuffer: ...
    def receive_string(self, minimum_ts: typing.SupportsInt = ..., blocking: bool = ...) -> str | None: ...
    @property
    def buffer_count(self) -> int: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def fd(self) -> int: ...
    @property
    def has_next(self) -> bool: ...
    @property
    def is_ended(self) -> bool: ...
    @property
    def is_sync(self) -> bool: ...
    @property
    def last_sent_iteration(self) -> int: ...
    @property
    def name(self) -> str: ...

class Control:
    def __init__(self, *args, **kwargs) -> None: ...

class ControlSnapshot:
    def __init__(self, *args, **kwargs) -> None: ...

class DataOverflow(IndexError): ...

class Inspector:
    def __init__(self, arg0: str) -> None: ...
    def control_snapshot(self, timeout: typing.SupportsFloat = ...) -> str: ...

class LogLevel:
    __members__: ClassVar[dict] = ...  # read-only
    DEBUG: ClassVar[LogLevel] = ...
    ERROR: ClassVar[LogLevel] = ...
    INFO: ClassVar[LogLevel] = ...
    WARNING: ClassVar[LogLevel] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Producer:
    def __init__(self, stream_name: str, buffer_size: typing.SupportsInt, buffer_count: typing.SupportsInt, sync: bool = ..., cancel_event: object = ..., polling_interval: typing.SupportsFloat = ..., context: str = ...) -> None: ...
    def end(self) -> None: ...
    def next_to_send(self, blocking: bool = ...) -> WriteBuffer: ...
    def send_string(self, message: str, blocking: bool = ..., release: bool = ...) -> bool: ...
    @property
    def buffer_count(self) -> int: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def fd(self) -> int: ...
    @property
    def is_ended(self) -> bool: ...
    @property
    def is_sync(self) -> bool: ...
    @property
    def last_sent_iteration(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def subscriber_count(self) -> int: ...

class ReadBuffer:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def read(self) -> bytes: ...
    @overload
    def read(self, count: typing.SupportsInt) -> bytes: ...
    def release(self) -> None: ...
    def seek(self, index: typing.SupportsInt) -> int: ...
    def tell(self) -> int: ...
    def __buffer__(self, *args, **kwargs): ...
    @overload
    def __getitem__(self, index: typing.SupportsInt) -> int: ...
    @overload
    def __getitem__(self, slice: slice) -> bytes: ...
    def __release_buffer__(self, *args, **kwargs): ...
    @property
    def buffer_count(self) -> int: ...
    @property
    def buffer_id(self) -> int: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def data_size(self) -> int: ...
    @property
    def data_timestamp(self) -> int: ...
    @property
    def iteration(self) -> int: ...

class ReleasedBuffer(RuntimeError): ...

class StreamExists(RuntimeError): ...

class StreamUnavailable(RuntimeError): ...

class ThreadingEventWrapper:
    def __init__(self, cancel_event: object) -> None: ...
    def is_set(self) -> bool: ...

class WriteBuffer:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def read(self) -> bytes: ...
    @overload
    def read(self, count: typing.SupportsInt) -> bytes: ...
    def seek(self, index: typing.SupportsInt) -> int: ...
    def send(self, *args, **kwargs): ...
    def tell(self) -> int: ...
    @overload
    def truncate(self) -> int: ...
    @overload
    def truncate(self, index: typing.SupportsInt) -> int: ...
    def write(self, value: bytes) -> None: ...
    def __buffer__(self, *args, **kwargs): ...
    @overload
    def __getitem__(self, index: typing.SupportsInt) -> int: ...
    @overload
    def __getitem__(self, slice: slice) -> bytes: ...
    def __release_buffer__(self, *args, **kwargs): ...
    @overload
    def __setitem__(self, index: typing.SupportsInt, value: typing.SupportsInt) -> None: ...
    @overload
    def __setitem__(self, slice: slice, value: bytes) -> None: ...
    @property
    def buffer_count(self) -> int: ...
    @property
    def buffer_id(self) -> int: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def data_size(self) -> int: ...
    @property
    def data_timestamp(self) -> int: ...
    @property
    def iteration(self) -> int: ...

def get_log_level() -> LogLevel: ...
def set_log_level(level: LogLevel) -> None: ...
