FROM rockylinux:8

RUN dnf install -y epel-release && \
    dnf install -y gcc-c++ make cmake ccache python38-devel && \
    dnf clean all && \
    rm -rf /var/cache/yum

WORKDIR /app/src
COPY requirements.txt /app/src/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app/src
RUN make
    
