FROM ubuntu:jammy

RUN apt-get update && \
    apt-get install -y g++ make cmake ccache python3-dev python3-pip

WORKDIR /app/src
COPY requirements.txt /app/src/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app/src
RUN make
    
